apiVersion: v1
kind: Service
metadata:
  name: proxies-service
  namespace: proxies-system
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
    - protocol: TCP
      port: 443
      targetPort: 443
    - protocol: TCP
      port: 25
      targetPort: 25
