apiVersion: v1
kind: Service
metadata:
  name: proxy-service
  namespace: proxy-system
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
    - name: smtp
      protocol: TCP
      port: 25
      targetPort: 25
